extends:
  - airbnb
  - airbnb-typescript
  - next/core-web-vitals
  - prettier
rules:
  react/jsx-props-no-spreading:
    - error
    - html: enforce
      custom: enforce
      explicitSpread: ignore
      exceptions:
        - Component
        - DefaultSeo
  jsx-a11y/anchor-is-valid:
    - error
    - components:
        - Link
      specialLink:
        - to
      aspects:
        - invalidHref
        - preferButton
overrides:
  - files:
      - '**/*'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ./tsconfig.json
      warnOnUnsupportedTypeScriptVersion: false
  - files:
      - '**/*.test.{tsx,ts,js}'
    extends:
      - airbnb
      - airbnb-typescript
      - next/core-web-vitals
      - plugin:jest/all
      - plugin:testing-library/react
      - plugin:jest-dom/recommended
      - prettier
  - files:
      - './{test,scripts}/**/*'
    rules:
      import/no-extraneous-dependencies: off
