module.exports = {
  mode: 'jit',
  purge: ['./src/**/*.{js,ts,jsx,tsx}'],
  darkMode: false,
  theme: {
    screens: {
      sm: '700px',
      md: '1008px',
    },
    colors: {
      background: '#000037',
      primary: '#09BDC6',
      secondary: '#EA00D9',
      'primary-dark': '#133E7C',
      'secondary-dark': '#711C91',
      'body-text': '#FFFFFF',
    },
    spacing: {
      px: '1px',
      0: '0',
      s: '4px',
      m: '8px',
      l: '16px',
      xl: '24px',
      xxl: '32px',
      xxxl: '48px',
    },
    borderRadius: {
      'none': '0',
      'sm': '4px',
      DEFAULT: '12px',
      'lg': '16px',
      'full': '9999px',
    },
    fontFamily: {
      sans: ['Blender Pro', 'Blender Pro Book'],
    },
    fontSize: {
      xs: ['0.75rem', { lineHeight: '1rem' }],
      sm: ['0.875rem', { lineHeight: '1.25rem' }],
      base: ['1rem', { lineHeight: '1.5rem' }],
      lg: ['1.125rem', { lineHeight: '1.75rem' }],
      xl: ['1.25rem', { lineHeight: '1.75rem' }],
      '2xl': ['1.5rem', { lineHeight: '2rem' }],
      '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
      '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      '5xl': ['3rem', { lineHeight: '1' }],
      '6xl': ['3.75rem', { lineHeight: '1' }],
      '7xl': ['4.5rem', { lineHeight: '1' }],
      '8xl': ['6rem', { lineHeight: '1' }],
      '9xl': ['8rem', { lineHeight: '1' }],
    },
  },
}
